// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type Album struct {
	ID              int64          `json:"id"`
	DeezerID        sql.NullString `json:"deezer_id"`
	Title           string         `json:"title"`
	NormalizedTitle string         `json:"normalized_title"`
	ArtistID        int64          `json:"artist_id"`
	ReleaseDate     sql.NullString `json:"release_date"`
	AlbumArtPath    sql.NullString `json:"album_art_path"`
	Genre           sql.NullString `json:"genre"`
	TotalTracks     sql.NullInt64  `json:"total_tracks"`
	CreatedAt       time.Time      `json:"created_at"`
}

type Artist struct {
	ID             int64          `json:"id"`
	DeezerID       sql.NullString `json:"deezer_id"`
	Name           string         `json:"name"`
	NormalizedName string         `json:"normalized_name"`
	CreatedAt      time.Time      `json:"created_at"`
}

type DownloadHistory struct {
	ID           string         `json:"id"`
	UserID       sql.NullInt64  `json:"user_id"`
	TrackID      sql.NullInt64  `json:"track_id"`
	Quality      sql.NullInt64  `json:"quality"`
	Status       sql.NullString `json:"status"`
	Service      sql.NullString `json:"service"`
	StartedAt    time.Time      `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
	ErrorMessage sql.NullString `json:"error_message"`
}

type Track struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	NormalizedTitle string         `json:"normalized_title"`
	ArtistID        sql.NullInt64  `json:"artist_id"`
	AlbumID         sql.NullInt64  `json:"album_id"`
	Duration        sql.NullInt64  `json:"duration"`
	TrackNumber     sql.NullInt64  `json:"track_number"`
	DiscNumber      sql.NullInt64  `json:"disc_number"`
	SampleRate      sql.NullInt64  `json:"sample_rate"`
	Bitrate         sql.NullInt64  `json:"bitrate"`
	Channels        sql.NullInt64  `json:"channels"`
	FilePath        string         `json:"file_path"`
	FileSize        sql.NullInt64  `json:"file_size"`
	Isrc            sql.NullString `json:"isrc"`
	Composer        sql.NullString `json:"composer"`
	CreatedAt       time.Time      `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	Email        sql.NullString `json:"email"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	LastLogin    sql.NullTime   `json:"last_login"`
	IsActive     sql.NullBool   `json:"is_active"`
}

type UserTrack struct {
	UserID      sql.NullInt64 `json:"user_id"`
	TrackID     sql.NullInt64 `json:"track_id"`
	SymlinkPath string        `json:"symlink_path"`
	LinkedDate  time.Time     `json:"linked_date"`
}
