// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	InsertTrack(ctx context.Context, arg InsertTrackParams) (Track, error)
	SearchTracksByTitle(ctx context.Context, query sql.NullString) ([]Track, error)
}

var _ Querier = (*Queries)(nil)
